spring.application.name=RouteMaster

# H2 Database
spring.datasource.url=jdbc:h2:mem:routemasterdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Log
logging.file.name=/app/logs/routemaster.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=RouteMasterSecretKeyForAviationSystemSuperSecure2025
jwt.expiration=900000
jwt.refresh.expiration=604800000

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
